update 20210515

diff --git a/book_app/cgi-bin/book_app b/book_app/cgi-bin/book_app
--- a/book_app/cgi-bin/book_app
+++ b/book_app/cgi-bin/book_app
@@ -6,6 +6,28 @@ echo ""
 # load small-shell path
 . ../descriptor/.small_shell_path
 
+IP_whitelisting="yes"
+
+# IP restriction check
+if [ "$IP_whitelisting" = "yes" ];then
+  whitelist_chk=`${small_shell_path}/bin/meta get.IP | grep -v "NO IP RESTRICTION"`
+  if [ "$whitelist_chk" ];then
+    for IP in $whitelist_chk
+    do
+      IP=`echo $IP | sed "s/*//g"`
+      if [[ ${REMOTE_ADDR} == ${IP}* ]];then
+        IP_chk_flag=yes
+        break
+      fi
+    done
+   
+    if [ ! "$IP_chk_flag" = "yes" ];then
+      echo "error: your IP is not allowed to access"
+      exit 1
+    fi
+  fi
+fi
+
 # auth for small-shell databox
 authkey="Ym9va19hcHA6ZWEyNGRiNjliYmVkNGIxNGQwMTFkNGIzODIyOWE5MzUwNDAzZTFjMgo="
 auth_req=`sudo -u small-shell ${small_shell_path}/bin/auth key_auth:${authkey} remote_addr:${REMOTE_ADDR}`
@@ -17,7 +39,6 @@ pin=`echo $auth_req | awk -F "," '{print $3}' | awk -F ":" '{print $2}'`
 param=`date +%s`
 param="$param:$RANDOM"
 count=1
-session_update="required"
 
 while [ -f ../tmp/${param} ]
 do
@@ -57,6 +78,10 @@ fi
 #----------------------------
 # routing to action scripts
 #----------------------------
+
+if [ ! "$req" ];then
+  req=get
+fi
 
 case "$req" in
 
